### ISSUE TITLE
Css rule matches all bootstrap rows in site

### ISSUE THREAD

**Issue by tbidwell** [oohoo/moodle-mod_tab#25]
There is a very generic css rule that sets the background color on all bootstrap rows in the whole site.
[styles.css](/oohoo/moodle-mod_tab/blob/master/styles.css#L59)
```css
.tab-specific-prefix .row {
   background-color: #eeeeee;
}
```

Can you please put some kind of prefix on this rule so it only matches rows inside this activity?

Thanks
